### ISSUE TITLE
Handle multiple edn forms, like jet

### ISSUE THREAD

**Issue by justone** [borkdude/puget-cli#1]
Thank you for this command line wrapper! This will provide a wonderful replacement to my usage of jet and [bat](https://github.com/sharkdp/bat).

One small thing, would it be possible to update it to support multiple edn forms, like jet does?

```
$ echo "{:foo :bar}{:second :edn}" | puget
{:foo :bar}
$ echo "{:foo :bar}{:second :edn}" | jet --pretty
{:foo :bar}
{:second :edn}
```

**Comment by borkdude** [comment]
Yeah, I think we can do this like jet. Are you in for a PR?

**Comment by justone** [comment]
Working up a PR right now...
