### ISSUE TITLE
Support for edn reader options

### ISSUE THREAD

**Issue by smessems** [borkdude/puget-cli#3]
Hi, would it be possible to also support the edn reader options, like jet does?

For example, I would have:
jet --edn-reader-opts '{:default tagged-literal}'

To avoid the clojure.lang.EdnReader$TaggedReader.readTagged exception, for example, if a log line contains something like: #function[clojure.core/into]
( actually, that {:default tagged-literal} might probably be worth to put as default in both tools - when reading input at command line context.

**Comment by borkdude** [comment]
@smessems I think you are right. Feel free to make a PR for this tool.

**Comment by borkdude** [comment]
Thank you. This is released as 0.0.3.

``` clojure
$ puget <<< '#foo [:bar]'
#foo [:bar]
```
